trigger:
  batch: true
  branches:
    include:
      - master
pr:
  autoCancel: true
stages:
  - stage: test_src
    dependsOn: []
    displayName: Test
    jobs:
      - job: go_tests
        displayName: Go Tests
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          GOBIN:  '$(GOPATH)/bin'
          GOPATH: '$(system.defaultWorkingDirectory)/gopath'
          modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'
        steps:
          - script: |
              mkdir -p '$(GOBIN)'
              mkdir -p '$(GOPATH)/pkg'
              mkdir -p '$(modulePath)'
              shopt -s extglob
              mv !(gopath) '$(modulePath)'
            displayName: 'Init workspace'
          - script: |
              go version
              GO111MODULE=on go get -u github.com/jstemmer/go-junit-report
              GO111MODULE=on go get -v ./...
            workingDirectory: '$(modulePath)'
            displayName: 'Download dependencies'
          - script: GO111MODULE=on go test -v ./... -coverprofile=coverage.txt -covermode=atomic 2>&1 | $GOPATH/bin/go-junit-report > test-golang-report.xml
            displayName: 'Run tests'
            workingDirectory: '$(modulePath)'
          - script: |
              bash <(curl -s https://codecov.io/bash)
            displayName: 'Update code coverage'
          - task: PublishTestResults@2
            displayName: 'Publish results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: |
                **/test-*.xml
                **/TEST-*.xml
              testRunTitle: 'Publish test results for $(Agent.JobName)'